version: '3.3'

services:

  backend:
    image: noble6/overwork_api:latest
    restart: always

  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  static_value: